# Form implementation generated from reading ui file '.\facereg.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Face(object):
    def setupUi(self, Face):
        Face.setObjectName("Face")
        Face.resize(600, 600)
        self.FaceReg = QtWidgets.QGroupBox(parent=Face)
        self.FaceReg.setGeometry(QtCore.QRect(50, 50, 500, 500))
        self.FaceReg.setObjectName("FaceReg")
        self.lbCamera = QtWidgets.QLabel(parent=self.FaceReg)
        self.lbCamera.setGeometry(QtCore.QRect(30, 30, 450, 450))
        self.lbCamera.setText("")
        self.lbCamera.setObjectName("lbCamera")

        self.retranslateUi(Face)
        QtCore.QMetaObject.connectSlotsByName(Face)

    def retranslateUi(self, Face):
        _translate = QtCore.QCoreApplication.translate
        Face.setWindowTitle(_translate("Face", "Form"))
        self.FaceReg.setTitle(_translate("Face", "Màn hình nhận diện"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Face = QtWidgets.QWidget()
    ui = Ui_Face()
    ui.setupUi(Face)
    Face.show()
    sys.exit(app.exec())
