# Form implementation generated from reading ui file '.\home.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(1400, 800)
        self.frame_14 = QtWidgets.QFrame(parent=Home)
        self.frame_14.setGeometry(QtCore.QRect(410, 250, 160, 160))
        self.frame_14.setStyleSheet("border-radius: 25px;\n"
"background-color: #5442b1;\n"
"color: white;\n"
"font-weight:bold;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_61 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_61.setGeometry(QtCore.QRect(20, 120, 120, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_62.setGeometry(QtCore.QRect(40, 20, 80, 80))
        self.label_62.setStyleSheet("border-image: url(:/assets/assets/icons/learning.png);")
        self.label_62.setText("")
        self.label_62.setObjectName("label_62")
        self.frame_17 = QtWidgets.QFrame(parent=Home)
        self.frame_17.setGeometry(QtCore.QRect(850, 440, 160, 160))
        self.frame_17.setStyleSheet("border-radius: 25px;\n"
"background-color: #5442b1;\n"
"color: white;\n"
"font-weight:bold;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_63 = QtWidgets.QLabel(parent=self.frame_17)
        self.label_63.setGeometry(QtCore.QRect(20, 120, 120, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(parent=self.frame_17)
        self.label_64.setGeometry(QtCore.QRect(40, 20, 80, 80))
        self.label_64.setStyleSheet("border-image: url(:/assets/assets/icons/exam.png);")
        self.label_64.setText("")
        self.label_64.setObjectName("label_64")
        self.frame_16 = QtWidgets.QFrame(parent=Home)
        self.frame_16.setGeometry(QtCore.QRect(850, 250, 160, 160))
        self.frame_16.setStyleSheet("border-radius: 25px;\n"
"background-color: #5442b1;\n"
"color: white;\n"
"font-weight:bold;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_65 = QtWidgets.QLabel(parent=self.frame_16)
        self.label_65.setGeometry(QtCore.QRect(20, 120, 120, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(parent=self.frame_16)
        self.label_66.setGeometry(QtCore.QRect(40, 20, 80, 80))
        self.label_66.setStyleSheet("border-image: url(:/assets/assets/icons/teacher.png);")
        self.label_66.setText("")
        self.label_66.setObjectName("label_66")
        self.frame_13 = QtWidgets.QFrame(parent=Home)
        self.frame_13.setGeometry(QtCore.QRect(630, 250, 160, 160))
        self.frame_13.setStyleSheet("border-radius: 25px;\n"
"background-color: #5442b1;\n"
"color: white;\n"
"font-weight:bold;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_67 = QtWidgets.QLabel(parent=self.frame_13)
        self.label_67.setGeometry(QtCore.QRect(20, 120, 120, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(parent=self.frame_13)
        self.label_68.setGeometry(QtCore.QRect(40, 20, 80, 80))
        self.label_68.setStyleSheet("border-image: url(:/assets/assets/icons/student.png);")
        self.label_68.setText("")
        self.label_68.setObjectName("label_68")
        self.frame_15 = QtWidgets.QFrame(parent=Home)
        self.frame_15.setGeometry(QtCore.QRect(630, 440, 160, 160))
        self.frame_15.setStyleSheet("border-radius: 25px;\n"
"background-color: #5442b1;\n"
"color: white;\n"
"font-weight:bold;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_69 = QtWidgets.QLabel(parent=self.frame_15)
        self.label_69.setGeometry(QtCore.QRect(20, 120, 120, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(parent=self.frame_15)
        self.label_70.setGeometry(QtCore.QRect(40, 20, 80, 80))
        self.label_70.setStyleSheet("border-image: url(:/assets/assets/icons/teach.png);")
        self.label_70.setText("")
        self.label_70.setObjectName("label_70")
        self.frame_18 = QtWidgets.QFrame(parent=Home)
        self.frame_18.setGeometry(QtCore.QRect(410, 440, 160, 160))
        self.frame_18.setStyleSheet("border-radius: 25px;\n"
"background-color: #5442b1;\n"
"color: white;\n"
"font-weight:bold;")
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label_71 = QtWidgets.QLabel(parent=self.frame_18)
        self.label_71.setGeometry(QtCore.QRect(20, 120, 120, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(parent=self.frame_18)
        self.label_72.setGeometry(QtCore.QRect(40, 20, 80, 80))
        self.label_72.setStyleSheet("border-image: url(:/assets/assets/icons/dictionary.png);")
        self.label_72.setText("")
        self.label_72.setObjectName("label_72")

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Form"))
        self.label_61.setText(_translate("Home", "Điểm danh"))
        self.label_63.setText(_translate("Home", "Thống kê"))
        self.label_65.setText(_translate("Home", "Giáo viên"))
        self.label_67.setText(_translate("Home", "Học sinh"))
        self.label_69.setText(_translate("Home", "Buổi học"))
        self.label_71.setText(_translate("Home", "Lớp học"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QWidget()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec())
