# Form implementation generated from reading ui file 'lession.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Lession(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1440, 800)
        Form.setMaximumSize(QtCore.QSize(1440, 800))
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(30, 30, 1371, 721))
        self.frame.setStyleSheet("#frame{\n"
"    background-color: rgb(231, 231, 231);\n"
"}\n"
"QPushButton{\n"
"padding: 15px 5px;\n"
"    background-color: #D5EDF9;\n"
"    border-color: black;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_title = QtWidgets.QLabel(parent=self.frame)
        self.label_title.setGeometry(QtCore.QRect(0, 0, 1371, 81))
        self.label_title.setStyleSheet("#label_title{\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    border-bottom-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.label_title.setObjectName("label_title")
        self.tt = QtWidgets.QFrame(parent=self.frame)
        self.tt.setGeometry(QtCore.QRect(30, 100, 441, 601))
        self.tt.setStyleSheet("#tt{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.tt.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tt.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tt.setObjectName("tt")
        self.label = QtWidgets.QLabel(parent=self.tt)
        self.label.setGeometry(QtCore.QRect(0, 0, 441, 51))
        self.label.setStyleSheet("color: rgb(255, 170, 0);\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.tt)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 91, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.tt)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 91, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.tt)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 91, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.tt)
        self.label_5.setGeometry(QtCore.QRect(20, 240, 91, 31))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(parent=self.tt)
        self.label_7.setGeometry(QtCore.QRect(20, 300, 101, 31))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(parent=self.tt)
        self.label_9.setGeometry(QtCore.QRect(20, 360, 91, 31))
        self.label_9.setObjectName("label_9")
        self.textEdit = QtWidgets.QTextEdit(parent=self.tt)
        self.textEdit.setGeometry(QtCore.QRect(130, 90, 241, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.tt)
        self.textEdit_2.setGeometry(QtCore.QRect(130, 140, 241, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.tt)
        self.textEdit_3.setGeometry(QtCore.QRect(130, 190, 241, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.tt)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 440, 331, 47))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.textEdit_5 = QtWidgets.QTextEdit(parent=self.tt)
        self.textEdit_5.setGeometry(QtCore.QRect(130, 240, 241, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(parent=self.tt)
        self.textEdit_6.setGeometry(QtCore.QRect(130, 300, 241, 31))
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_7 = QtWidgets.QTextEdit(parent=self.tt)
        self.textEdit_7.setGeometry(QtCore.QRect(130, 360, 241, 31))
        self.textEdit_7.setObjectName("textEdit_7")
        self.table_bh = QtWidgets.QFrame(parent=self.frame)
        self.table_bh.setGeometry(QtCore.QRect(500, 100, 841, 601))
        self.table_bh.setStyleSheet("#table_bh{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.table_bh.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.table_bh.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.table_bh.setObjectName("table_bh")
        self.label_10 = QtWidgets.QLabel(parent=self.table_bh)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 91, 31))
        self.label_10.setObjectName("label_10")
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.table_bh)
        self.comboBox_2.setGeometry(QtCore.QRect(120, 20, 121, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.textEdit_4 = QtWidgets.QTextEdit(parent=self.table_bh)
        self.textEdit_4.setGeometry(QtCore.QRect(250, 20, 161, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.table_bh)
        self.pushButton_5.setGeometry(QtCore.QRect(420, 10, 111, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.table_bh)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 821, 521))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_title.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">QUẢN LÝ THÔNG TIN BUỔI HỌC</span></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Thông tin buổi học</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Mã buổi học</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Giờ bắt đầu</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\"> Giờ kết thúc</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Ngày</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Tên giảng viên</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Tên môn học</span></p></body></html>"))
        self.pushButton_3.setText(_translate("Form", "Thêm mới"))
        self.pushButton_2.setText(_translate("Form", "Cập nhật"))
        self.pushButton_4.setText(_translate("Form", "Xóa"))
        self.pushButton.setText(_translate("Form", "Làm mới"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Tìm kiếm theo:</span></p></body></html>"))
        self.pushButton_5.setText(_translate("Form", "Tìm kiếm"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Mã buổi học"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Giờ bắt đầu"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Giờ kết thúc"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Ngày"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Tên giảng viên"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Tên môn học"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Lession()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
