# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(845, 435)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("background-color: #D5EDF9;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(280, 0, 781, 531))
        self.frame_2.setStyleSheet("background-color:#5442B1;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.GridLayout = QtWidgets.QFrame(parent=self.frame_2)
        self.GridLayout.setGeometry(QtCore.QRect(80, 160, 401, 121))
        self.GridLayout.setAutoFillBackground(False)
        self.GridLayout.setStyleSheet("background-color:#D5EDF9;\n"
"border-radius: 10px;\n"
"")
        self.GridLayout.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.GridLayout.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.GridLayout.setObjectName("GridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.GridLayout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txt_taikhoan = QtWidgets.QTextEdit(parent=self.GridLayout)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.txt_taikhoan.setFont(font)
        self.txt_taikhoan.setStyleSheet("background-color: white;\n"
"border: 2px solid black;\n"
"font-size: 18px;\n"
"border-radius: 0;\n"
"padding: 5px 5px;")
        self.txt_taikhoan.setLineWidth(1)
        self.txt_taikhoan.setMidLineWidth(0)
        self.txt_taikhoan.setObjectName("txt_taikhoan")
        self.verticalLayout.addWidget(self.txt_taikhoan)
        self.txt_matkhau = QtWidgets.QTextEdit(parent=self.GridLayout)
        self.txt_matkhau.setStyleSheet("background-color: white;\n"
"border: 2px solid black;\n"
"font-size: 18px;\n"
"border-radius: 0;\n"
"padding: 5px 5px;")
        self.txt_matkhau.setObjectName("txt_matkhau")
        self.verticalLayout.addWidget(self.txt_matkhau)
        self.btn_login = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_login.setGeometry(QtCore.QRect(310, 310, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setAutoFillBackground(False)
        self.btn_login.setStyleSheet("background-color: #D5EDF9; color: #5442B1;font-size: 20px; font-weight: bold;\n")
        icon = QtGui.QIcon.fromTheme("accept")
        self.btn_login.setIcon(icon)
        self.btn_login.setObjectName("btn_login")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setGeometry(QtCore.QRect(50, 100, 221, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(80)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #D5EDF9;\n"
"font-size: 30px; font-weight: bold;\n")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 221, 161))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #5442B1")
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 231, 161))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("color: #FFFFFF;\n"
"background-color: none;\n"
"")
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_taikhoan.setPlaceholderText(_translate("MainWindow", "Tài khoản"))
        self.txt_matkhau.setPlaceholderText(_translate("MainWindow", "Mật khẩu"))
        self.btn_login.setText(_translate("MainWindow", "Đăng nhập"))
        self.label.setText(_translate("MainWindow", "ĐĂNG NHẬP"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">NHÓM 9</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">NHÓM 9</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    MainWindow1=MainWindow
    ui.setupUi(MainWindow1)
    MainWindow.show()
    sys.exit(app.exec())
