# Form implementation generated from reading ui file '.\ui_capimge.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StudentImage(object):
    def setupUi(self, StudentImage):
        StudentImage.setObjectName("StudentImage")
        StudentImage.resize(1359, 661)
        self.frame = QtWidgets.QFrame(parent=StudentImage)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1361, 831))
        self.frame.setStyleSheet("#frame{\n"
"    background-color: #D5EDF9;\n"
"}\n"
"#grbx_thongtin{\n"
"    background-color: white;\n"
"    color: #5442B1;\n"
"    font-size: 25px;\n"
"    border: 3px solid #5442B1;\n"
"    border-radius: 10px\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.grbx_thongtin = QtWidgets.QGroupBox(parent=self.frame)
        self.grbx_thongtin.setGeometry(QtCore.QRect(40, 30, 1311, 621))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.grbx_thongtin.setFont(font)
        self.grbx_thongtin.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.grbx_thongtin.setAutoFillBackground(False)
        self.grbx_thongtin.setStyleSheet("font-size:14px")
        self.grbx_thongtin.setTitle("")
        self.grbx_thongtin.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.grbx_thongtin.setFlat(False)
        self.grbx_thongtin.setCheckable(False)
        self.grbx_thongtin.setObjectName("grbx_thongtin")
        self.lb_hinhanh = QtWidgets.QLabel(parent=self.grbx_thongtin)
        self.lb_hinhanh.setGeometry(QtCore.QRect(400, 100, 250, 201))
        self.lb_hinhanh.setStyleSheet("border: 1px solid black;\n"
"")
        self.lb_hinhanh.setText("")
        self.lb_hinhanh.setObjectName("lb_hinhanh")
        self.label = QtWidgets.QLabel(parent=self.grbx_thongtin)
        self.label.setGeometry(QtCore.QRect(400, 330, 251, 20))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.btn_dong = QtWidgets.QPushButton(parent=self.grbx_thongtin)
        self.btn_dong.setGeometry(QtCore.QRect(820, 490, 121, 51))
        self.btn_dong.setObjectName("btn_dong")
        self.btn_xoa = QtWidgets.QPushButton(parent=self.grbx_thongtin)
        self.btn_xoa.setGeometry(QtCore.QRect(60, 450, 111, 41))
        self.btn_xoa.setObjectName("btn_xoa")
        self.listhinhanh = QtWidgets.QListWidget(parent=self.grbx_thongtin)
        self.listhinhanh.setGeometry(QtCore.QRect(60, 100, 291, 341))
        self.listhinhanh.setStyleSheet("font-size:20px")
        self.listhinhanh.setObjectName("listhinhanh")
        self.label_2 = QtWidgets.QLabel(parent=self.grbx_thongtin)
        self.label_2.setGeometry(QtCore.QRect(220, 20, 921, 61))
        self.label_2.setStyleSheet("font-size:25px;\n"
"font-weight: bold;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(parent=self.grbx_thongtin)
        self.widget.setGeometry(QtCore.QRect(680, 100, 601, 371))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.lb_cam = QtWidgets.QLabel(parent=self.widget)
        self.lb_cam.setGeometry(QtCore.QRect(10, 10, 581, 351))
        self.lb_cam.setStyleSheet("border:1px solid black;\n"
"")
        self.lb_cam.setObjectName("lb_cam")
        self.btn_mocam = QtWidgets.QPushButton(parent=self.grbx_thongtin)
        self.btn_mocam.setGeometry(QtCore.QRect(680, 490, 121, 51))
        self.btn_mocam.setObjectName("btn_mocam")
        self.btn_chupanh = QtWidgets.QPushButton(parent=self.grbx_thongtin)
        self.btn_chupanh.setGeometry(QtCore.QRect(1160, 490, 121, 51))
        self.btn_chupanh.setObjectName("btn_chupanh")
        self.btn_xacnhan = QtWidgets.QPushButton(parent=self.grbx_thongtin)
        self.btn_xacnhan.setGeometry(QtCore.QRect(1160, 550, 121, 51))
        self.btn_xacnhan.setObjectName("btn_xacnhan")
        self.lb_numimg = QtWidgets.QLabel(parent=self.grbx_thongtin)
        self.lb_numimg.setGeometry(QtCore.QRect(60, 510, 101, 51))
        self.lb_numimg.setObjectName("lb_numimg")

        self.retranslateUi(StudentImage)
        QtCore.QMetaObject.connectSlotsByName(StudentImage)

    def retranslateUi(self, StudentImage):
        _translate = QtCore.QCoreApplication.translate
        StudentImage.setWindowTitle(_translate("StudentImage", "Form"))
        self.label.setText(_translate("StudentImage", "Xem trước hình ảnh"))
        self.btn_dong.setText(_translate("StudentImage", "Đóng Camera"))
        self.btn_xoa.setText(_translate("StudentImage", "Xóa"))
        self.label_2.setText(_translate("StudentImage", "HÌNH ẢNH"))
        self.lb_cam.setText(_translate("StudentImage", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_mocam.setText(_translate("StudentImage", "Mở camera"))
        self.btn_chupanh.setText(_translate("StudentImage", "Chụp ảnh"))
        self.btn_xacnhan.setText(_translate("StudentImage", "Xác nhận"))
        self.lb_numimg.setText(_translate("StudentImage", "Số ảnh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StudentImage = QtWidgets.QWidget()
    ui = Ui_StudentImage()
    ui.setupUi(StudentImage)
    StudentImage.show()
    sys.exit(app.exec())
