# Form implementation generated from reading ui file '.\sesson_selection.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SessonSelection(object):
    def setupUi(self, SessonSelection):
        SessonSelection.setObjectName("SessonSelection")
        SessonSelection.resize(860, 669)
        SessonSelection.setMaximumSize(QtCore.QSize(1440, 800))
        self.frame1 = QtWidgets.QFrame(parent=SessonSelection)
        self.frame1.setGeometry(QtCore.QRect(10, 10, 841, 601))
        self.frame1.setStyleSheet("#table_bh{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame1.setObjectName("frame1")
        self.label_10 = QtWidgets.QLabel(parent=self.frame1)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 91, 31))
        self.label_10.setObjectName("label_10")
        self.cb_timkiem = QtWidgets.QComboBox(parent=self.frame1)
        self.cb_timkiem.setGeometry(QtCore.QRect(120, 20, 121, 31))
        self.cb_timkiem.setObjectName("cb_timkiem")
        self.cb_timkiem.addItem("")
        self.cb_timkiem.addItem("")
        self.cb_timkiem.addItem("")
        self.cb_timkiem.addItem("")
        self.txt_timkiem = QtWidgets.QTextEdit(parent=self.frame1)
        self.txt_timkiem.setGeometry(QtCore.QRect(250, 20, 161, 31))
        self.txt_timkiem.setObjectName("txt_timkiem")
        self.btn_timkiem = QtWidgets.QPushButton(parent=self.frame1)
        self.btn_timkiem.setGeometry(QtCore.QRect(420, 20, 111, 31))
        self.btn_timkiem.setObjectName("btn_timkiem")
        self.table_bh = QtWidgets.QTableWidget(parent=self.frame1)
        self.table_bh.setGeometry(QtCore.QRect(10, 70, 821, 521))
        self.table_bh.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.table_bh.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_bh.setObjectName("table_bh")
        self.table_bh.setColumnCount(8)
        self.table_bh.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_bh.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_bh.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_bh.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_bh.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_bh.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_bh.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_bh.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_bh.setHorizontalHeaderItem(7, item)
        self.table_bh.horizontalHeader().setDefaultSectionSize(100)
        self.btn_accept = QtWidgets.QPushButton(parent=SessonSelection)
        self.btn_accept.setGeometry(QtCore.QRect(390, 620, 111, 31))
        self.btn_accept.setObjectName("btn_accept")

        self.retranslateUi(SessonSelection)
        QtCore.QMetaObject.connectSlotsByName(SessonSelection)

    def retranslateUi(self, SessonSelection):
        _translate = QtCore.QCoreApplication.translate
        SessonSelection.setWindowTitle(_translate("SessonSelection", "Form"))
        self.label_10.setText(_translate("SessonSelection", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Tìm kiếm theo:</span></p></body></html>"))
        self.cb_timkiem.setItemText(0, _translate("SessonSelection", "Mã môn học"))
        self.cb_timkiem.setItemText(1, _translate("SessonSelection", "Tên môn học"))
        self.cb_timkiem.setItemText(2, _translate("SessonSelection", "Giảng viên"))
        self.cb_timkiem.setItemText(3, _translate("SessonSelection", "Lớp"))
        self.btn_timkiem.setText(_translate("SessonSelection", "Tìm kiếm"))
        item = self.table_bh.horizontalHeaderItem(0)
        item.setText(_translate("SessonSelection", "Mã buổi học"))
        item = self.table_bh.horizontalHeaderItem(1)
        item.setText(_translate("SessonSelection", "Tên môn học"))
        item = self.table_bh.horizontalHeaderItem(2)
        item.setText(_translate("SessonSelection", "Tuần"))
        item = self.table_bh.horizontalHeaderItem(3)
        item.setText(_translate("SessonSelection", "Giảng viên"))
        item = self.table_bh.horizontalHeaderItem(4)
        item.setText(_translate("SessonSelection", "Tiết bắt đầu"))
        item = self.table_bh.horizontalHeaderItem(5)
        item.setText(_translate("SessonSelection", "Tiết kết thúc"))
        item = self.table_bh.horizontalHeaderItem(6)
        item.setText(_translate("SessonSelection", "Ngày"))
        item = self.table_bh.horizontalHeaderItem(7)
        item.setText(_translate("SessonSelection", "Lớp"))
        self.btn_accept.setText(_translate("SessonSelection", "Chọn buổi học"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SessonSelection = QtWidgets.QWidget()
    ui = Ui_SessonSelection()
    ui.setupUi(SessonSelection)
    SessonSelection.show()
    sys.exit(app.exec())
