# Form implementation generated from reading ui file '.\student_info.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StudentInfo(object):
    def setupUi(self, StudentInfo):
        StudentInfo.setObjectName("StudentInfo")
        StudentInfo.resize(954, 741)
        self.fr_thongtin = QtWidgets.QFrame(parent=StudentInfo)
        self.fr_thongtin.setGeometry(QtCore.QRect(30, 40, 891, 661))
        self.fr_thongtin.setStyleSheet("#frame{\n"
"    border: 1px solid black\n"
"}\n"
"QPushButton{\n"
"    padding: 15px 5px;\n"
"    background-color: #D5EDF9;\n"
"}\n"
"#gridLayout{\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.fr_thongtin.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fr_thongtin.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_thongtin.setObjectName("fr_thongtin")
        self.grbx_canhan = QtWidgets.QGroupBox(parent=self.fr_thongtin)
        self.grbx_canhan.setGeometry(QtCore.QRect(20, 60, 521, 591))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.grbx_canhan.setFont(font)
        self.grbx_canhan.setStyleSheet("QLabel, QPushButton{\n"
"    font-size: 14px;\n"
"}")
        self.grbx_canhan.setObjectName("grbx_canhan")
        self.lb_hoten = QtWidgets.QLabel(parent=self.grbx_canhan)
        self.lb_hoten.setGeometry(QtCore.QRect(10, 20, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lb_hoten.setFont(font)
        self.lb_hoten.setObjectName("lb_hoten")
        self.lb_namsinh = QtWidgets.QLabel(parent=self.grbx_canhan)
        self.lb_namsinh.setGeometry(QtCore.QRect(10, 120, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lb_namsinh.setFont(font)
        self.lb_namsinh.setObjectName("lb_namsinh")
        self.lb_cccd = QtWidgets.QLabel(parent=self.grbx_canhan)
        self.lb_cccd.setGeometry(QtCore.QRect(10, 170, 57, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lb_cccd.setFont(font)
        self.lb_cccd.setObjectName("lb_cccd")
        self.lb_gioitinh = QtWidgets.QLabel(parent=self.grbx_canhan)
        self.lb_gioitinh.setGeometry(QtCore.QRect(10, 220, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lb_gioitinh.setFont(font)
        self.lb_gioitinh.setObjectName("lb_gioitinh")
        self.lb_email = QtWidgets.QLabel(parent=self.grbx_canhan)
        self.lb_email.setGeometry(QtCore.QRect(10, 270, 56, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lb_email.setFont(font)
        self.lb_email.setObjectName("lb_email")
        self.lb_sdt = QtWidgets.QLabel(parent=self.grbx_canhan)
        self.lb_sdt.setGeometry(QtCore.QRect(10, 320, 44, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lb_sdt.setFont(font)
        self.lb_sdt.setObjectName("lb_sdt")
        self.txt_mssv = QtWidgets.QTextEdit(parent=self.grbx_canhan)
        self.txt_mssv.setEnabled(False)
        self.txt_mssv.setGeometry(QtCore.QRect(90, 20, 411, 41))
        font = QtGui.QFont()
        self.txt_mssv.setFont(font)
        self.txt_mssv.setReadOnly(True)
        self.txt_mssv.setObjectName("txt_mssv")
        self.txt_namsinh = QtWidgets.QTextEdit(parent=self.grbx_canhan)
        self.txt_namsinh.setGeometry(QtCore.QRect(90, 120, 411, 41))
        font = QtGui.QFont()
        self.txt_namsinh.setFont(font)
        self.txt_namsinh.setReadOnly(True)
        self.txt_namsinh.setPlaceholderText("")
        self.txt_namsinh.setObjectName("txt_namsinh")
        self.txt_cccd = QtWidgets.QTextEdit(parent=self.grbx_canhan)
        self.txt_cccd.setGeometry(QtCore.QRect(90, 170, 411, 41))
        font = QtGui.QFont()
        self.txt_cccd.setFont(font)
        self.txt_cccd.setReadOnly(True)
        self.txt_cccd.setPlaceholderText("")
        self.txt_cccd.setObjectName("txt_cccd")
        self.txt_email = QtWidgets.QTextEdit(parent=self.grbx_canhan)
        self.txt_email.setGeometry(QtCore.QRect(90, 270, 411, 41))
        font = QtGui.QFont()
        self.txt_email.setFont(font)
        self.txt_email.setReadOnly(True)
        self.txt_email.setPlaceholderText("")
        self.txt_email.setObjectName("txt_email")
        self.txt_sdt = QtWidgets.QTextEdit(parent=self.grbx_canhan)
        self.txt_sdt.setGeometry(QtCore.QRect(90, 320, 411, 41))
        font = QtGui.QFont()
        self.txt_sdt.setFont(font)
        self.txt_sdt.setReadOnly(True)
        self.txt_sdt.setPlaceholderText("")
        self.txt_sdt.setObjectName("txt_sdt")
        self.txt_malop = QtWidgets.QTextEdit(parent=self.grbx_canhan)
        self.txt_malop.setGeometry(QtCore.QRect(90, 370, 411, 41))
        font = QtGui.QFont()
        self.txt_malop.setFont(font)
        self.txt_malop.setReadOnly(True)
        self.txt_malop.setPlaceholderText("")
        self.txt_malop.setObjectName("txt_malop")
        self.lb_lophoc = QtWidgets.QLabel(parent=self.grbx_canhan)
        self.lb_lophoc.setGeometry(QtCore.QRect(10, 370, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lb_lophoc.setFont(font)
        self.lb_lophoc.setObjectName("lb_lophoc")
        self.txt_hoten = QtWidgets.QTextEdit(parent=self.grbx_canhan)
        self.txt_hoten.setGeometry(QtCore.QRect(90, 70, 411, 41))
        font = QtGui.QFont()
        self.txt_hoten.setFont(font)
        self.txt_hoten.setReadOnly(True)
        self.txt_hoten.setPlaceholderText("")
        self.txt_hoten.setObjectName("txt_hoten")
        self.lb_hoten_2 = QtWidgets.QLabel(parent=self.grbx_canhan)
        self.lb_hoten_2.setGeometry(QtCore.QRect(10, 70, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lb_hoten_2.setFont(font)
        self.lb_hoten_2.setObjectName("lb_hoten_2")
        self.txt_gioitinh = QtWidgets.QTextEdit(parent=self.grbx_canhan)
        self.txt_gioitinh.setGeometry(QtCore.QRect(90, 220, 131, 41))
        font = QtGui.QFont()
        self.txt_gioitinh.setFont(font)
        self.txt_gioitinh.setReadOnly(True)
        self.txt_gioitinh.setPlaceholderText("")
        self.txt_gioitinh.setObjectName("txt_gioitinh")
        self.lb_thongtin = QtWidgets.QLabel(parent=self.fr_thongtin)
        self.lb_thongtin.setGeometry(QtCore.QRect(4, 10, 551, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lb_thongtin.setFont(font)
        self.lb_thongtin.setStyleSheet("font-size: 20px;\n"
"font-weight: bold;")
        self.lb_thongtin.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_thongtin.setObjectName("lb_thongtin")
        self.lbImage = QtWidgets.QLabel(parent=self.fr_thongtin)
        self.lbImage.setGeometry(QtCore.QRect(630, 70, 160, 160))
        self.lbImage.setText("")
        self.lbImage.setObjectName("lbImage")

        self.retranslateUi(StudentInfo)
        QtCore.QMetaObject.connectSlotsByName(StudentInfo)

    def retranslateUi(self, StudentInfo):
        _translate = QtCore.QCoreApplication.translate
        StudentInfo.setWindowTitle(_translate("StudentInfo", "Form"))
        self.grbx_canhan.setTitle(_translate("StudentInfo", "Thông tin cá nhân"))
        self.lb_hoten.setText(_translate("StudentInfo", "Mã SV:"))
        self.lb_namsinh.setText(_translate("StudentInfo", "Năm sinh:"))
        self.lb_cccd.setText(_translate("StudentInfo", "CCCD:"))
        self.lb_gioitinh.setText(_translate("StudentInfo", "Giới tính:"))
        self.lb_email.setText(_translate("StudentInfo", "Email:"))
        self.lb_sdt.setText(_translate("StudentInfo", "SĐT:"))
        self.txt_mssv.setHtml(_translate("StudentInfo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">3</span></p></body></html>"))
        self.lb_lophoc.setText(_translate("StudentInfo", "Lớp"))
        self.lb_hoten_2.setText(_translate("StudentInfo", "Họ tên:"))
        self.lb_thongtin.setText(_translate("StudentInfo", "THÔNG TIN SINH VIÊN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StudentInfo = QtWidgets.QWidget()
    ui = Ui_StudentInfo()
    ui.setupUi(StudentInfo)
    StudentInfo.show()
    sys.exit(app.exec())
